spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: ninja
    password: udemy
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true
    #schema: schema.sql
    #data: data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      dialect: org.hibernate.dialect.H2Dialect
       
# enable H2 web console and set url for web console
# http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /console

