spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: ninja
    password: udemy
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true
    #schema: schema.sql
    #data: data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      dialect: org.hibernate.dialect.H2Dialect
       
# enable H2 web console and set url for web console
# http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /console
  
# spring.datasource.url=jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.datasource.initialize=true
# spring.datasource.schema=schema.sql
# spring.datasource.data=data.sql
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.path=/myconsole
# spring.h2.console.enabled=true
